### ISSUE TITLE
Hamctrl release command fails with "Unknown error"

### ISSUE THREAD

**Issue by jweibel22** [lunarway/release-manager#131] opened 2020-01-27 10:17 UTC
Occasionally (quite often recently) hamctrl release fails with an "unknown error".
To my understanding this can happen when multiple releases are being carried out concurrently because the git push operations that happens in the release-manager must be done serializably. (because the local branch must be rebased/merged with the remote branch before pushing)??

The problem is proportional to the amount of hamctrl activity we have, which I'm guessing is increasing, and it would be nice with a fix.

One possible fix:
We could e.g. introduce an intermediary queue and return an OK to the client once the request has been submitted to the queue and have a dispatcher do the git commits. This would avoid the concurrency issue (if the dispatcher is single-threaded). Also if any transient errors with git occurs, the dispatcher can keep retrying until the problem has been resolved without being forced to timeout because a user is waiting on the other side.
The current process is async, when hamtrl returns to the client it's just saying "thank you for your request it will be processed (by flux) asap", thus introducing an extra layer of async should not alter the user experience.

**Comment by Crevil** [comment] 2020-01-27 10:58
The `unknown error` is any internal error from witch we cannot recover.
It can be caused by multiple failure modes, where one of them is, as you mention, racing writes to the config repository.

There have been a bug after a performance optimisation implemented in #122 that caused this error to come when configuration for the provided service was not found. This can be due to the wrong branch name, environment etc. This was fixed in #128 but is yet to be released.

We have seen the issue you mention 5 times over the past 30 days across ~1350 releases (less than 1%).

This is not to say, that it is not a problem that we should solve, but the problem is not as huge as it might seem.

We have some ideas in the pipeline already regarding a more asynchronous flow to avoid this and this will properly by the way to go forward.

**Comment by jweibel22** [comment] 2020-01-27 11:13
ok I see, I must have hit the unknown error for for different reasons :-)

**Closed** 2020-03-09 12:01 UTC
